---
- name: Check If java is already installed or not
  shell: "java -version | grep -w 'OpenJDK' | awk '{print $3}'"
  register: java_installed

- name: Installed java version
  debug: "msg={{java_installed.stdout}}"

- block:
  - name: Download and Unarchive Java
    unarchive:
        src: "{{ java_url }}"
        dest: "{{ home_parent_directory }}"
        copy: no
  - name: Create JAVA symlink to /usr/bin
    file:
        src: "{{ home_parent_directory }}/jdk-{{ java_version }}/bin/java"
        dest: /usr/bin/java
        state: link
  - name: Set JAVA HOME and JAVA PATH
    lineinfile:
        dest: "{{ java_env_file }}"
        line: "{{ item.line }}"
        create: yes
        state: present
    with_items:
        - { line: 'JAVA_HOME={{ home_parent_directory }}/jdk-{{ java_version }}' }
        - { line: 'PATH=$PATH:$JAVA_HOME/bin' }
  - name: Exports java env file for make JAVA_HOME available globally
    shell: "source {{ java_env_file }}"  